version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  api:
    build: ./api
    container_name: api
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/droplater
      - REDIS_HOST=redis
    depends_on:
      - mongo
      - redis

  worker:
    build: ./worker
    container_name: worker
    depends_on:
      - mongo
      - redis

  sink:
    build: ./sink
    container_name: sink
    ports:
      - "4000:4000"
    depends_on:
      - redis

  admin:
    build: ./admin
    container_name: admin
    ports:
      - "5173:80"
    depends_on:
      - api
